"""Built-in deterministic templates for the demo specs.

Three template sets:
  * ``taskstore`` — a storage library (Task + TaskStore), no CLI.
  * ``tasklist``  — a CLI that ``requires`` taskstore and imports it at runtime.
  * ``example``   — the original self-contained task-list (store + CLI in one pkg).
"""

from __future__ import annotations

import json

from ..base import RenderRequest


def _m(path: str, contents: str) -> dict:
    return {"path": path, "action": "write", "contents": contents, "root": "module"}


def _provenance(request: RenderRequest, package: str) -> dict:
    """A generated provenance file that ties emitted code to the spec it came from.

    Because its contents derive from every unit rendered so far (id, title, spec and
    acceptance text), any meaningful spec change changes the generated code — which is
    what makes a required module's ``requiredModuleCodeHash`` move and cascade to
    dependents, mirroring how a real model renderer would emit different code.
    """
    payload = {
        "module": request.module,
        "stack": request.stack,
        "units": request.units_so_far,
    }
    body = json.dumps(payload, indent=2, sort_keys=True)
    return _m(
        f"src/{package}/_mint_provenance.py",
        '"""Generated by mint. Provenance of the spec this code was rendered from."""\n\n'
        f"PROVENANCE = {body}\n",
    )


def _c(path: str, contents: str) -> dict:
    return {"path": path, "action": "write", "contents": contents, "root": "conformance"}


# A conftest that makes the module's own src importable and also honours
# MINT_REQUIRED_SRC so generated code can import its required modules at test time.
_CONFTEST = '''from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

for extra in os.environ.get("MINT_REQUIRED_SRC", "").split(os.pathsep):
    if extra:
        sys.path.insert(0, extra)
'''

_GITIGNORE = '''__pycache__/
*.py[cod]
.pytest_cache/
tasks.json
'''


def _store_module(package: str) -> str:
    return f'''from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path


@dataclass(frozen=True)
class Task:
    text: str
    completed: bool = False


class TaskStore:
    """File-backed list of tasks for {package}."""

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)

    def add_task(self, text: str) -> Task:
        task = Task(text=text, completed=False)
        tasks = self.list_tasks()
        tasks.append(task)
        self._save(tasks)
        return task

    def list_tasks(self) -> list[Task]:
        if not self.path.exists():
            return []
        data = json.loads(self.path.read_text(encoding="utf-8"))
        return [Task(text=item["text"], completed=bool(item["completed"])) for item in data]

    def _save(self, tasks: list[Task]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(
                [{{"text": task.text, "completed": task.completed}} for task in tasks],
                indent=2,
            ),
            encoding="utf-8",
        )
'''


# --------------------------------------------------------------------------- #
# taskstore: storage library
# --------------------------------------------------------------------------- #


def build_taskstore(request: RenderRequest) -> list[dict]:
    package = "taskstore"
    rendered = request.rendered_unit_ids
    files: list[dict] = [
        _m(".gitignore", _GITIGNORE),
        _m("pyproject.toml", _lib_pyproject("taskstore", package)),
        _m("README.md", _readme("taskstore", "library API: Task, TaskStore")),
        _m(
            f"src/{package}/__init__.py",
            f'"""Generated storage library."""\n\n'
            f"from .store import Task, TaskStore\n\n"
            f'__all__ = ["Task", "TaskStore"]\n',
        ),
        _m(f"src/{package}/store.py", _store_module(package)),
        _provenance(request, package),
        _m("tests/conftest.py", _CONFTEST),
    ]
    if "FR1" in rendered:
        files.append(_m("tests/test_fr1.py", _store_unit_fr1(package)))
    if "FR2" in rendered:
        files.append(_m("tests/test_fr2.py", _store_unit_fr2(package)))

    files.append(_taskstore_conformance(request, package))
    return files


def _store_unit_fr1(package: str) -> str:
    return f'''from __future__ import annotations

from {package} import TaskStore


def test_add_creates_incomplete_task(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")

    task = store.add_task("Buy milk")

    assert task.text == "Buy milk"
    assert task.completed is False
    assert store.list_tasks()[0].text == "Buy milk"
    assert store.list_tasks()[0].completed is False
'''


def _store_unit_fr2(package: str) -> str:
    return f'''from __future__ import annotations

from {package} import TaskStore


def test_list_preserves_insertion_order(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")

    store.add_task("Buy milk")
    store.add_task("Write notes")

    assert [task.text for task in store.list_tasks()] == ["Buy milk", "Write notes"]
'''


def _taskstore_conformance(request: RenderRequest, package: str) -> dict:
    unit = request.current_unit_id
    if unit == "FR1":
        body = f'''from __future__ import annotations

from {package} import Task, TaskStore


def test_public_api_add_then_list(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")
    store.add_task("Buy milk")

    tasks = TaskStore(tmp_path / "tasks.json").list_tasks()

    assert tasks == [Task(text="Buy milk", completed=False)]
'''
    elif unit == "FR2":
        body = f'''from __future__ import annotations

from {package} import TaskStore


def test_public_api_preserves_order(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")
    store.add_task("Buy milk")
    store.add_task("Write notes")

    reloaded = TaskStore(tmp_path / "tasks.json")
    assert [t.text for t in reloaded.list_tasks()] == ["Buy milk", "Write notes"]
'''
    else:
        body = _generic_conformance(package)
    return _c(f"{unit}/test_{unit.lower()}.py", body)


# --------------------------------------------------------------------------- #
# tasklist: CLI that requires taskstore
# --------------------------------------------------------------------------- #


def build_tasklist(request: RenderRequest) -> list[dict]:
    package = "tasklist"
    env_var = "TASKLIST_STORE"
    command = "tasklist-cli"
    rendered = request.rendered_unit_ids
    files: list[dict] = [
        _m(".gitignore", _GITIGNORE),
        _m("pyproject.toml", _cli_pyproject("tasklist", package, command, ["taskstore"])),
        _m("README.md", _readme("tasklist", f"public command: {command}")),
        _m(
            f"src/{package}/__init__.py",
            '"""Generated task-list CLI (requires taskstore)."""\n',
        ),
        _m(f"src/{package}/cli.py", _tasklist_cli(package, env_var)),
        _provenance(request, package),
        _m("tests/conftest.py", _CONFTEST),
    ]
    if "FR1" in rendered:
        files.append(_m("tests/test_fr1.py", _tasklist_unit_fr1(package, env_var)))
    if "FR2" in rendered:
        files.append(_m("tests/test_fr2.py", _tasklist_unit_fr2(package, env_var)))

    files.append(_tasklist_conformance(request, package, env_var))
    return files


def _tasklist_cli(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Sequence

from taskstore import TaskStore


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="{package}")
    subparsers = parser.add_subparsers(dest="command")

    add_parser = subparsers.add_parser("add")
    add_parser.add_argument("text")

    subparsers.add_parser("list")
    return parser


def store_from_env() -> TaskStore:
    path = Path(os.environ.get("{env_var}", "tasks.json"))
    return TaskStore(path)


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    store = store_from_env()

    if args.command == "add":
        task = store.add_task(args.text)
        print(f"[ ] {{task.text}}")
        return 0

    if args.command == "list":
        for task in store.list_tasks():
            marker = "x" if task.completed else " "
            print(f"[{{marker}}] {{task.text}}")
        return 0

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _tasklist_unit_fr1(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

from {package} import cli


def test_add_prints_incomplete_marker(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("{env_var}", str(tmp_path / "tasks.json"))

    rc = cli.main(["add", "Buy milk"])

    assert rc == 0
    assert "[ ] Buy milk" in capsys.readouterr().out
'''


def _tasklist_unit_fr2(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

from {package} import cli


def test_list_preserves_insertion_order(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("{env_var}", str(tmp_path / "tasks.json"))
    cli.main(["add", "Buy milk"])
    cli.main(["add", "Write notes"])
    capsys.readouterr()

    rc = cli.main(["list"])

    out = capsys.readouterr().out
    assert rc == 0
    assert out.index("Buy milk") < out.index("Write notes")
'''


def _tasklist_conformance(request: RenderRequest, package: str, env_var: str) -> dict:
    unit = request.current_unit_id
    runner = f'''from __future__ import annotations

import os
import subprocess
import sys


def run_cli(tmp_path, *args):
    env = os.environ.copy()
    env["{env_var}"] = str(tmp_path / "tasks.json")
    return subprocess.run(
        [sys.executable, "-m", "{package}.cli", *args],
        env=env,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
'''
    if unit == "FR1":
        body = runner + '''

def test_add_then_list_shows_incomplete_task(tmp_path):
    add = run_cli(tmp_path, "add", "Buy milk")
    assert add.returncode == 0, add.stderr

    listed = run_cli(tmp_path, "list")
    assert listed.returncode == 0, listed.stderr
    assert "[ ] Buy milk" in listed.stdout
'''
    elif unit == "FR2":
        body = runner + '''

def test_list_preserves_insertion_order(tmp_path):
    assert run_cli(tmp_path, "add", "Buy milk").returncode == 0
    assert run_cli(tmp_path, "add", "Write notes").returncode == 0

    listed = run_cli(tmp_path, "list")
    assert listed.returncode == 0, listed.stderr
    assert listed.stdout.index("Buy milk") < listed.stdout.index("Write notes")
'''
    else:
        body = _generic_conformance(package)
    return _c(f"{unit}/test_{unit.lower()}.py", body)


# --------------------------------------------------------------------------- #
# example: original self-contained task-list (store + CLI in one package)
# --------------------------------------------------------------------------- #


def build_example(request: RenderRequest) -> list[dict]:
    package = "example"
    env_var = "EXAMPLE_TODO_STORE"
    command = "example-todo"
    rendered = request.rendered_unit_ids
    files: list[dict] = [
        _m(".gitignore", _GITIGNORE),
        _m("pyproject.toml", _cli_pyproject("example", package, command, [])),
        _m("README.md", _readme("example", f"public command: {command}")),
        _m(
            f"src/{package}/__init__.py",
            '"""Generated self-contained task-list."""\n\n'
            "from .store import Task, TaskStore\n\n"
            '__all__ = ["Task", "TaskStore"]\n',
        ),
        _m(f"src/{package}/store.py", _store_module(package)),
        _m(f"src/{package}/cli.py", _example_cli(package, env_var)),
        _provenance(request, package),
        _m("tests/conftest.py", _CONFTEST),
    ]
    if "FR1" in rendered:
        files.append(_m("tests/test_fr1.py", _example_unit_fr1(package, env_var)))
    if "FR2" in rendered:
        files.append(_m("tests/test_fr2.py", _example_unit_fr2(package, env_var)))

    unit = request.current_unit_id
    runner = f'''from __future__ import annotations

import os
import subprocess
import sys


def run_cli(tmp_path, *args):
    env = os.environ.copy()
    env["{env_var}"] = str(tmp_path / "tasks.json")
    return subprocess.run(
        [sys.executable, "-m", "{package}.cli", *args],
        env=env,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
'''
    if unit == "FR1":
        body = runner + '''

def test_add_then_list_shows_incomplete_task(tmp_path):
    add = run_cli(tmp_path, "add", "Buy milk")
    assert add.returncode == 0, add.stderr

    listed = run_cli(tmp_path, "list")
    assert listed.returncode == 0, listed.stderr
    assert "[ ] Buy milk" in listed.stdout
'''
    elif unit == "FR2":
        body = runner + '''

def test_list_preserves_insertion_order(tmp_path):
    assert run_cli(tmp_path, "add", "Buy milk").returncode == 0
    assert run_cli(tmp_path, "add", "Write notes").returncode == 0

    listed = run_cli(tmp_path, "list")
    assert listed.returncode == 0, listed.stderr
    assert listed.stdout.index("Buy milk") < listed.stdout.index("Write notes")
'''
    else:
        body = _generic_conformance(package)
    files.append(_c(f"{unit}/test_{unit.lower()}.py", body))
    return files


def _example_unit_fr1(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

from {package} import TaskStore
from {package} import cli


def test_add_creates_incomplete_task(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")

    task = store.add_task("Buy milk")

    assert task.text == "Buy milk"
    assert task.completed is False
    assert store.list_tasks()[0].text == "Buy milk"
    assert store.list_tasks()[0].completed is False


def test_cli_add_then_list_shows_incomplete_task(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("{env_var}", str(tmp_path / "tasks.json"))

    add_rc = cli.main(["add", "Buy milk"])
    add_out = capsys.readouterr().out
    list_rc = cli.main(["list"])
    list_out = capsys.readouterr().out

    assert add_rc == 0
    assert "[ ] Buy milk" in add_out
    assert list_rc == 0
    assert "[ ] Buy milk" in list_out


def test_cli_without_command_prints_help(capsys):
    rc = cli.main([])

    assert rc == 0
    assert "usage:" in capsys.readouterr().out
'''


def _example_unit_fr2(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

from {package} import TaskStore
from {package} import cli


def test_list_preserves_insertion_order(tmp_path):
    store = TaskStore(tmp_path / "tasks.json")

    store.add_task("Buy milk")
    store.add_task("Write notes")

    assert [task.text for task in store.list_tasks()] == ["Buy milk", "Write notes"]


def test_cli_list_preserves_insertion_order(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("{env_var}", str(tmp_path / "tasks.json"))
    assert cli.main(["add", "Buy milk"]) == 0
    assert cli.main(["add", "Write notes"]) == 0
    capsys.readouterr()

    rc = cli.main(["list"])
    out = capsys.readouterr().out

    assert rc == 0
    assert out.index("Buy milk") < out.index("Write notes")


def test_cli_list_with_no_tasks_prints_no_rows(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("{env_var}", str(tmp_path / "tasks.json"))

    rc = cli.main(["list"])
    out = capsys.readouterr().out

    assert rc == 0
    assert out == ""
'''


def _example_cli(package: str, env_var: str) -> str:
    return f'''from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Sequence

from .store import TaskStore


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="{package}")
    subparsers = parser.add_subparsers(dest="command")

    add_parser = subparsers.add_parser("add")
    add_parser.add_argument("text")

    subparsers.add_parser("list")
    return parser


def store_from_env() -> TaskStore:
    path = Path(os.environ.get("{env_var}", "tasks.json"))
    return TaskStore(path)


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    store = store_from_env()

    if args.command == "add":
        task = store.add_task(args.text)
        print(f"[ ] {{task.text}}")
        return 0

    if args.command == "list":
        for task in store.list_tasks():
            marker = "x" if task.completed else " "
            print(f"[{{marker}}] {{task.text}}")
        return 0

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


# --------------------------------------------------------------------------- #
# shared bits
# --------------------------------------------------------------------------- #


def _generic_conformance(package: str) -> str:
    return f'''from __future__ import annotations


def test_generated_package_imports():
    __import__("{package}")
'''


def _readme(module: str, blurb: str) -> str:
    return f"# {module}\n\nGenerated by `mint`.\n\n{blurb}.\n"


def _lib_pyproject(name: str, package: str) -> str:
    return f'''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
'''


def _cli_pyproject(name: str, package: str, command: str, requires: list[str]) -> str:
    deps = ", ".join(f'"{req}"' for req in requires)
    return f'''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [{deps}]

[project.scripts]
{command} = "{package}.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
'''
